"""
Conversation-related data models.

This module defines Pydantic models for conversation entities:
- Message: Individual messages in a conversation
- Question: Questions generated by the system
- Answer: User responses to questions
- Session: Conversation session metadata
- Chunk: Text chunks for RAG system
"""

from pydantic import BaseModel, Field
from typing import Dict, List, Optional
from datetime import datetime
from enum import Enum
import uuid


class ConversationState(str, Enum):
    """Conversation state machine states."""
    START = "start"
    FUNCTIONALITY = "functionality"
    USERS = "users"
    DEMOGRAPHICS = "demographics"
    DESIGN = "design"
    MARKET = "market"
    TECHNICAL = "technical"
    REVIEW = "review"
    COMPLETE = "complete"


class MessageRole(str, Enum):
    """Message roles."""
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class Message(BaseModel):
    """Individual message in a conversation."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str
    role: MessageRole
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: Dict = Field(default_factory=dict)

    class Config:
        json_schema_extra = {
            "example": {
                "id": "msg-123",
                "session_id": "session-456",
                "role": "user",
                "content": "I want to build a task management app",
                "timestamp": "2024-01-01T12:00:00Z",
                "metadata": {}
            }
        }


class Question(BaseModel):
    """Question generated by the system."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    category: str
    text: str
    context: List[str] = Field(default_factory=list)
    is_followup: bool = False
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        json_schema_extra = {
            "example": {
                "id": "q-123",
                "category": "functionality",
                "text": "What is the main purpose of your product?",
                "context": [],
                "is_followup": False,
                "timestamp": "2024-01-01T12:00:00Z"
            }
        }


class Answer(BaseModel):
    """User response to a question."""
    question_id: str
    text: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)

    class Config:
        json_schema_extra = {
            "example": {
                "question_id": "q-123",
                "text": "A collaborative task management platform for teams",
                "timestamp": "2024-01-01T12:01:00Z",
                "confidence": 1.0
            }
        }


class Session(BaseModel):
    """Conversation session metadata."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    started_at: datetime = Field(default_factory=datetime.utcnow)
    last_updated: datetime = Field(default_factory=datetime.utcnow)
    status: str = "active"  # active, complete, paused
    state: ConversationState = ConversationState.START
    investigation_progress: Dict = Field(default_factory=dict)
    metadata: Dict = Field(default_factory=dict)
    provider: Optional[str] = None
    model_id: Optional[str] = None
    skipped_questions: List[str] = Field(default_factory=list)  # Track skipped question IDs

    class Config:
        json_schema_extra = {
            "example": {
                "id": "session-456",
                "started_at": "2024-01-01T12:00:00Z",
                "last_updated": "2024-01-01T12:05:00Z",
                "status": "active",
                "state": "functionality",
                "investigation_progress": {"functionality": 0.5},
                "metadata": {},
                "provider": "groq",
                "model_id": "llama2-70b-4096"
            }
        }


class Chunk(BaseModel):
    """Text chunk for RAG system."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    content: str
    embedding: Optional[List[float]] = None
    session_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    category: str
    metadata: Dict = Field(default_factory=dict)

    class Config:
        json_schema_extra = {
            "example": {
                "id": "chunk-789",
                "content": "Q: What is your product? A: A task management app",
                "embedding": None,
                "session_id": "session-456",
                "timestamp": "2024-01-01T12:00:00Z",
                "category": "functionality",
                "metadata": {}
            }
        }
